[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:inference-server]
command=sh -c "uvicorn inference_server:app --host 0.0.0.0 --port ${PORT:-8080}"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:kafka-consumer]
command=python kafka_consumer.py
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
